import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { access, readFile } from "node:fs/promises";
import test from "node:test";

test("the literal Text Tailwind matrix matches its deterministic source", () => {
  execFileSync(process.execPath, ["scripts/generate-text-tailwind.mjs", "--check"], {
    cwd: process.cwd(),
  });
});

test("records the complete literal-Tailwind Text closure", async () => {
  const manifest = JSON.parse(await readFile("scraps-parity.json", "utf8"));
  const text = manifest.modules.find(({ name }) => name === "text");
  const registry = JSON.parse(await readFile("registry.json", "utf8"));
  const item = registry.items.find(({ name }) => name === "text");
  assert.equal(text.completion.state, "complete");
  assert.equal(text.completion.complete, true);
  assert.match(text.completion.note, /production browser behavior/);
  assert.deepEqual(text.local.implementationPaths, [
    "src/components/ui/heading.tsx",
    "src/components/ui/prose.tsx",
    "src/components/ui/text.tsx",
  ]);
  assert.deepEqual(text.local.figmaNodes, []);
  assert.deepEqual(item.dependencies, [
    "@fontsource-variable/roboto-mono@5.2.9",
    "@fontsource/rubik@5.2.8",
  ]);
  assert.deepEqual(
    item.files.map(({ path }) => path),
    [
      "src/components/ui/roboto-mono.css",
      "src/components/ui/rubik.css",
      "src/components/ui/container-query-context.ts",
      "src/components/ui/layout-style-engine.ts",
      "src/components/ui/text-tailwind.ts",
      "src/components/ui/text.tsx",
      "src/components/ui/heading.tsx",
      "src/components/ui/prose.tsx",
      "src/components/ui/text-index.ts",
    ],
  );
  await access("src/components/ui/text-tailwind.ts");
});

test("uses generated literal candidates without a runtime CSS compiler", async () => {
  const text = await readFile("src/components/ui/text.tsx", "utf8");
  const heading = await readFile("src/components/ui/heading.tsx", "utf8");
  const prose = await readFile("src/components/ui/prose.tsx", "utf8");
  const tailwind = await readFile("src/components/ui/text-tailwind.ts", "utf8");
  assert.match(tailwind, /Generated by scripts\/generate-text-tailwind/);
  assert.match(tailwind, /\[font-size:var\(--scraps-text-font-size\)\]/);
  assert.match(tailwind, /min-\[1200px\]:!\[--scraps-text-font-size:24px\]/);
  assert.match(tailwind, /@\[576px\]:\[--scraps-text-display:none\]/);
  assert.doesNotMatch(tailwind, /min-\[[^\]]+\]:!\[(?:font-size|line-height|display|text-align):/);
  assert.match(text, /createTextTailwindClassName/);
  assert.match(text, /\[text-decoration:line-through_underline\]/);
  assert.match(text, /\[text-decoration:line-through_underline_dotted\]/);
  assert.match(text, /\[word-break:normal\]/);
  assert.match(text, /\[word-break:break-word\]/);
  assert.doesNotMatch(text, /decoration-\[line-through|break-words|break-normal/);
  assert.match(text, /export function headingStaticClassName/);
  assert.match(heading, /headingStaticClassName/);
  assert.match(heading, /\[font-weight:inherit\]/);
  assert.doesNotMatch(heading, /font-\[inherit\]/);
  assert.doesNotMatch(heading, /textStaticClassName/);
  assert.doesNotMatch(
    `${text}\n${heading}\n${prose}`,
    /<style|text\.module\.css|text-style-engine/,
  );
  assert.match(
    prose,
    /\[&_ul:not\(\[role=listbox\],\[role=grid\],\[role=menu\]\):last-child\]:mb-0/,
  );
  assert.match(prose, /code:not\(pre_code\)/);
  assert.doesNotMatch(
    prose,
    /code:not\(pre_code\)\]:text-\[length:inherit\]|code:not\(pre_code\)\]:font-\[425\]/,
  );
  assert.match(prose, /\[&_kbd\]:\[font-size:12px\]/);
  assert.doesNotMatch(prose, /\[&_kbd\]:text-xs/);
});

test("publishes the exact Roboto Mono family without a global Tailwind theme", async () => {
  const registry = JSON.parse(await readFile("registry.json", "utf8"));
  const item = registry.items.find(({ name }) => name === "text");
  const text = await readFile("src/components/ui/text.tsx", "utf8");
  const prose = await readFile("src/components/ui/prose.tsx", "utf8");

  assert.ok(item.files.some(({ path }) => path === "src/components/ui/text.tsx"));
  assert.ok(item.files.some(({ path }) => path === "src/components/ui/prose.tsx"));
  assert.ok(item.files.some(({ path }) => path === "src/components/ui/roboto-mono.css"));
  assert.ok(item.dependencies.includes("@fontsource-variable/roboto-mono@5.2.9"));
  assert.match(text, /ROBOTO_MONO_FONT_FAMILY_CLASS_NAMES/);
  assert.match(text, /Roboto_Mono/);
  assert.match(text, /Roboto_Mono.*,Monaco,Consolas.*Courier_New.*,monospace/);
  assert.match(prose, /ROBOTO_MONO_FONT_FAMILY_CLASS_NAMES\.proseInlineCode/);
  assert.match(prose, /ROBOTO_MONO_FONT_FAMILY_CLASS_NAMES\.proseKbd/);
  assert.doesNotMatch(`${text}\n${prose}`, /(?:^|["'\s:])font-mono(?:["'\s]|$)/m);
});

test("declares the pinned Sentry font families, ranges, and subsets", async () => {
  const rubik = (await readFile("src/components/ui/rubik.css", "utf8")).replace(/\s+/g, " ");
  const robotoMono = (await readFile("src/components/ui/roboto-mono.css", "utf8")).replace(
    /\s+/g,
    " ",
  );

  assert.equal((rubik.match(/font-family: "Rubik"/g) ?? []).length, 8);
  assert.equal((rubik.match(/font-weight: 400/g) ?? []).length, 4);
  assert.equal((rubik.match(/font-weight: 500 600/g) ?? []).length, 4);
  assert.equal((rubik.match(/font-display: swap/g) ?? []).length, 8);
  assert.match(
    rubik,
    /U\+0000-00FF, U\+0131, U\+0152-0153, U\+02BB-02BC, U\+02C6, U\+02DA, U\+02DC, U\+2000-206F, U\+2074, U\+20AC, U\+2122, U\+2191, U\+2193, U\+2212, U\+2215, U\+FEFF, U\+FFFD/,
  );
  assert.match(
    rubik,
    /U\+0100-024F, U\+0259, U\+1E00-1EFF, U\+2020, U\+20A0-20AB, U\+20AD-20CF, U\+2113, U\+2C60-2C7F, U\+A720-A7FF/,
  );
  assert.match(rubik, /U\+0301, U\+0400-045F, U\+0490-0491, U\+04B0-04B1, U\+2116/);
  assert.match(
    rubik,
    /U\+0460-052F, U\+1C80-1C88, U\+20B4, U\+2DE0-2DFF, U\+A640-A69F, U\+FE2E-FE2F/,
  );

  assert.equal((robotoMono.match(/font-family: "Roboto Mono"/g) ?? []).length, 6);
  assert.equal((robotoMono.match(/font-weight: 425 600/g) ?? []).length, 6);
  assert.equal((robotoMono.match(/font-display: swap/g) ?? []).length, 6);
  assert.match(
    robotoMono,
    /U\+0000-00FF, U\+0131, U\+0152-0153, U\+02BB-02BC, U\+02C6, U\+02DA, U\+02DC, U\+0304, U\+0308, U\+0329, U\+2000-206F, U\+2074, U\+20AC, U\+2122, U\+2191, U\+2193, U\+2212, U\+2215, U\+FEFF, U\+FFFD/,
  );
  assert.match(
    robotoMono,
    /U\+0100-02AF, U\+0304, U\+0308, U\+0329, U\+1E00-1E9F, U\+1EF2-1EFF, U\+2020, U\+20A0-20AB, U\+20AD-20CF, U\+2113, U\+2C60-2C7F, U\+A720-A7FF/,
  );
  assert.match(
    robotoMono,
    /U\+0102-0103, U\+0110-0111, U\+0128-0129, U\+0168-0169, U\+01A0-01A1, U\+01AF-01B0, U\+0300-0301, U\+0303-0304, U\+0308-0309, U\+0323, U\+0329, U\+1EA0-1EF9, U\+20AB/,
  );
  assert.match(robotoMono, /U\+0370-03FF/);
  assert.match(robotoMono, /U\+0301, U\+0400-045F, U\+0490-0491, U\+04B0-04B1, U\+2116/);
  assert.match(
    robotoMono,
    /U\+0460-052F, U\+1C80-1C88, U\+20B4, U\+2DE0-2DFF, U\+A640-A69F, U\+FE2E-FE2F/,
  );
  assert.doesNotMatch(`${rubik}\n${robotoMono}`, /@import/);

  for (const asset of [
    "node_modules/@fontsource/rubik/files/rubik-latin-400-normal.woff2",
    "node_modules/@fontsource/rubik/files/rubik-latin-500-normal.woff2",
    "node_modules/@fontsource/rubik/files/rubik-latin-ext-400-normal.woff2",
    "node_modules/@fontsource/rubik/files/rubik-latin-ext-500-normal.woff2",
    "node_modules/@fontsource/rubik/files/rubik-cyrillic-400-normal.woff2",
    "node_modules/@fontsource/rubik/files/rubik-cyrillic-500-normal.woff2",
    "node_modules/@fontsource/rubik/files/rubik-cyrillic-ext-400-normal.woff2",
    "node_modules/@fontsource/rubik/files/rubik-cyrillic-ext-500-normal.woff2",
    "node_modules/@fontsource-variable/roboto-mono/files/roboto-mono-latin-wght-normal.woff2",
    "node_modules/@fontsource-variable/roboto-mono/files/roboto-mono-latin-ext-wght-normal.woff2",
    "node_modules/@fontsource-variable/roboto-mono/files/roboto-mono-vietnamese-wght-normal.woff2",
    "node_modules/@fontsource-variable/roboto-mono/files/roboto-mono-greek-wght-normal.woff2",
    "node_modules/@fontsource-variable/roboto-mono/files/roboto-mono-cyrillic-wght-normal.woff2",
    "node_modules/@fontsource-variable/roboto-mono/files/roboto-mono-cyrillic-ext-wght-normal.woff2",
  ]) {
    await access(asset);
  }
});
