// Generated by scripts/generate-layout-tailwind.mjs. Edit the generator instead.
import type { CSSProperties } from "react";

import {
  LAYOUT_CONTAINER_ORDER,
  LAYOUT_VIEWPORT_ORDER,
  isLayoutResponsiveValue,
  sanitizeLayoutCssValue,
  type LayoutContainerBreakpoint,
  type LayoutResponsive,
  type LayoutResponsiveBreakpoint,
  type LayoutResponsiveKey,
  type LayoutTheme,
  type LayoutViewportBreakpoint,
} from "./layout-style-engine";

export type LayoutProperty = "container-type" | "display" | "position" | "inset" | "top" | "bottom" | "left" | "right" | "overflow" | "overflow-x" | "overflow-y" | "overscroll-behavior" | "pointer-events" | "cursor" | "contain" | "padding" | "padding-top" | "padding-bottom" | "padding-left" | "padding-right" | "margin" | "margin-top" | "margin-bottom" | "margin-left" | "margin-right" | "background" | "border-radius" | "border-top-left-radius" | "border-top-right-radius" | "border-bottom-right-radius" | "border-bottom-left-radius" | "width" | "min-width" | "max-width" | "height" | "min-height" | "max-height" | "grid-area" | "grid-row" | "grid-column" | "order" | "flex" | "flex-grow" | "flex-shrink" | "flex-basis" | "align-self" | "justify-self" | "border-top" | "border-bottom" | "border-left" | "border-right" | "visibility" | "white-space" | "row-gap" | "column-gap" | "flex-direction" | "flex-wrap" | "justify-content" | "align-items" | "grid-template-columns" | "grid-template-rows" | "grid-template-areas" | "grid-auto-columns" | "grid-auto-rows" | "grid-auto-flow" | "align-content" | "justify-items" | "box-shadow";

export interface LayoutTailwindDeclaration<T = unknown> {
  property: LayoutProperty;
  value: LayoutResponsive<T> | undefined;
  resolve?: ((
    value: never,
    breakpoint: LayoutResponsiveBreakpoint | undefined,
    theme: LayoutTheme
  ) => string | undefined) | undefined;
}

type CustomProperties = CSSProperties & Record<`--${string}`, string>;
type ResolvedValues = {
  base?: string;
  container: Record<string, string | undefined>;
  screen: Record<string, string | undefined>;
};
type ResolvedDeclarations = Map<LayoutProperty, ResolvedValues>;
export interface LayoutActiveBreakpoints {
  container: LayoutContainerBreakpoint;
  viewport: LayoutViewportBreakpoint;
}

const finiteValueGroups: readonly (readonly string[])[] = [
  [
    "normal",
    "inline-size",
    "size"
  ],
  [
    "block",
    "inline",
    "inline-block",
    "flex",
    "inline-flex",
    "grid",
    "inline-grid",
    "contents",
    "none"
  ],
  [
    "static",
    "relative",
    "absolute",
    "fixed",
    "sticky"
  ],
  [
    "visible",
    "hidden",
    "scroll",
    "auto"
  ],
  [
    "contain",
    "auto",
    "none"
  ],
  [
    "0px",
    "2px",
    "4px",
    "6px",
    "8px",
    "12px",
    "16px",
    "24px",
    "32px"
  ],
  [
    "0px",
    "2px",
    "4px",
    "6px",
    "8px",
    "12px",
    "16px",
    "24px",
    "32px",
    "0",
    "auto"
  ],
  [
    "var(--background)",
    "var(--card)",
    "var(--secondary)",
    "var(--popover)"
  ],
  [
    "0px",
    "3px",
    "4px",
    "5px",
    "6px",
    "8px",
    "12px",
    "16px",
    "999px"
  ],
  [
    "none",
    "1px solid var(--scraps-theme-border-primary)",
    "1px solid var(--scraps-theme-border-secondary)",
    "1px solid var(--scraps-theme-border-accent)",
    "1px solid var(--scraps-theme-border-danger)",
    "1px solid var(--scraps-theme-border-promotion)",
    "1px solid var(--scraps-theme-border-success)",
    "1px solid var(--scraps-theme-border-warning)"
  ],
  [
    "visible",
    "hidden",
    "collapse"
  ],
  [
    "break-spaces",
    "normal",
    "nowrap",
    "pre",
    "pre-line",
    "pre-wrap"
  ],
  [
    "row",
    "row-reverse",
    "column",
    "column-reverse"
  ],
  [
    "nowrap",
    "wrap",
    "wrap-reverse"
  ],
  [
    "flex-start",
    "flex-end",
    "start",
    "end",
    "center",
    "space-between",
    "space-around",
    "space-evenly",
    "stretch",
    "left",
    "right"
  ],
  [
    "flex-start",
    "flex-end",
    "center",
    "baseline",
    "stretch",
    "start",
    "end"
  ],
  [
    "row",
    "column",
    "row dense",
    "column dense"
  ],
  [
    "flex-start",
    "flex-end",
    "start",
    "end",
    "center",
    "space-between",
    "space-around",
    "space-evenly",
    "stretch"
  ],
  [
    "start",
    "end",
    "center",
    "stretch"
  ],
  [
    "var(--scraps-theme-shadow-low, 0px 1px 0px 0px #0000200f)",
    "var(--scraps-theme-shadow-medium, 0px 2px 0px 1px #10103008, 0px 1px 0px 0px #10103008)",
    "var(--scraps-theme-shadow-high, 0px 4px 0px 2px #10103008, 0px 1px 0px 1px #10103008)"
  ]
];
const finitePropertyGroups: Partial<Record<LayoutProperty, number>> = {
  "container-type": 0,
  "display": 1,
  "position": 2,
  "overflow": 3,
  "overflow-x": 3,
  "overflow-y": 3,
  "overscroll-behavior": 4,
  "padding-top": 5,
  "padding-bottom": 5,
  "padding-left": 5,
  "padding-right": 5,
  "margin-top": 6,
  "margin-bottom": 6,
  "margin-left": 6,
  "margin-right": 6,
  "background": 7,
  "border-top-left-radius": 8,
  "border-top-right-radius": 8,
  "border-bottom-right-radius": 8,
  "border-bottom-left-radius": 8,
  "border-top": 9,
  "border-bottom": 9,
  "border-left": 9,
  "border-right": 9,
  "visibility": 10,
  "white-space": 11,
  "row-gap": 5,
  "column-gap": 5,
  "flex-direction": 12,
  "flex-wrap": 13,
  "justify-content": 14,
  "align-items": 15,
  "grid-auto-flow": 16,
  "align-content": 17,
  "justify-items": 18,
  "box-shadow": 19
};

function resolveValue<T>(
  declaration: LayoutTailwindDeclaration<T>,
  value: T | undefined,
  breakpoint: LayoutResponsiveBreakpoint | undefined,
  theme: LayoutTheme
): string | undefined {
  const resolved = declaration.resolve
    ? declaration.resolve(value as never, breakpoint, theme)
    : value;
  return sanitizeLayoutCssValue(resolved);
}

function variableName(prefix: string, property: LayoutProperty): `--${string}` {
  return `--scraps-layout-${prefix}-${property}`;
}

function propertyVariableName(property: LayoutProperty): `--${string}` {
  return `--scraps-layout-${property}`;
}

function isFinitePropertyValue(property: LayoutProperty, value: string): boolean {
  const groupIndex = finitePropertyGroups[property];
  return groupIndex !== undefined && finiteValueGroups[groupIndex].includes(value);
}

function tailwindValue(value: string): string {
  return value.replaceAll(" ", "_");
}

function literalClass(property: LayoutProperty, value: string, prefix = ""): string {
  return `${prefix}[${property}:${tailwindValue(value)}]`;
}

function resolveDeclaration(
  declaration: LayoutTailwindDeclaration,
  theme: LayoutTheme
): ResolvedValues | undefined {
  const { value } = declaration;
  if (value === undefined) return undefined;
  const values: ResolvedValues = { container: {}, screen: {} };
  if (!isLayoutResponsiveValue(value)) {
    values.base = resolveValue(declaration, value, undefined, theme);
    return values.base === undefined ? undefined : values;
  }

  let found = false;
  const write = (
    key: LayoutResponsiveKey,
    breakpoint: LayoutResponsiveBreakpoint,
    scope: "container" | "screen"
  ) => {
    const resolved = resolveValue(declaration, value[key], breakpoint, theme);
    if (resolved === undefined) return;
    found = true;
    if (key === "zero" || values.base === undefined) {
      values.base = resolved;
    } else {
      values[scope][key] = resolved;
    }
  };
  for (const key of LAYOUT_CONTAINER_ORDER) write(key, key, "container");
  for (const { key, token } of LAYOUT_VIEWPORT_ORDER) write(key, token, "screen");
  return found ? values : undefined;
}

function resolveDeclarations(
  declarations: readonly LayoutTailwindDeclaration[],
  theme: LayoutTheme
): ResolvedDeclarations {
  const resolvedByProperty: ResolvedDeclarations = new Map();
  for (const declaration of declarations) {
    const values = resolveDeclaration(declaration, theme);
    if (!values) continue;
    resolvedByProperty.set(declaration.property, values);
  }
  return resolvedByProperty;
}

function activeDeclarationValue(
  values: ResolvedValues,
  active: LayoutActiveBreakpoints
): string | undefined {
  let resolved = values.base;
  const containerIndex = LAYOUT_CONTAINER_ORDER.indexOf(active.container);
  for (let index = 1; index <= containerIndex; index++) {
    const key = LAYOUT_CONTAINER_ORDER[index];
    if (key !== undefined && values.container[key] !== undefined) {
      resolved = values.container[key];
    }
  }
  const viewportIndex = LAYOUT_VIEWPORT_ORDER.findIndex(
    ({ token }) => token === active.viewport
  );
  for (let index = 0; index <= viewportIndex; index++) {
    const key = LAYOUT_VIEWPORT_ORDER[index]?.key;
    if (key !== undefined && values.screen[key] !== undefined) {
      resolved = values.screen[key];
    }
  }
  return resolved;
}

function resolveActiveDeclarations(
  resolvedByProperty: ResolvedDeclarations,
  active: LayoutActiveBreakpoints
): ResolvedDeclarations {
  const activeDeclarations: ResolvedDeclarations = new Map();
  for (const [property, values] of resolvedByProperty) {
    const resolved = activeDeclarationValue(values, active);
    if (resolved !== undefined) {
      activeDeclarations.set(property, {
        base: resolved,
        container: {},
        screen: {},
      });
    }
  }
  return activeDeclarations;
}

function appendSingleDeclarationClasses(
  classes: string[],
  style: CustomProperties,
  property: LayoutProperty,
  values: ResolvedValues,
  theme: LayoutTheme
): void {
  const useResponsiveVariables =
    Object.values(values.container).some(value => value !== undefined) ||
    Object.values(values.screen).some(value => value !== undefined);
  if (values.base !== undefined) {
    if (isFinitePropertyValue(property, values.base) && !useResponsiveVariables) {
      classes.push(literalClass(property, values.base));
    } else {
      const propertyVariable = propertyVariableName(property);
      const baseVariable = variableName("base", property);
      style[baseVariable] = values.base;
      classes.push(
        `[${propertyVariable}:var(${baseVariable})]`,
        `[${property}:var(${propertyVariable})]`
      );
    }
  }
  for (const key of LAYOUT_CONTAINER_ORDER.slice(1)) {
    const value = values.container[key];
    if (value === undefined) continue;
    const prefix = `@[${theme.container[key]}]:`;
    const variable = variableName(`container-${key}`, property);
    style[variable] = value;
    classes.push(`${prefix}[${propertyVariableName(property)}:var(${variable})]`);
  }
  for (const { key, token } of LAYOUT_VIEWPORT_ORDER) {
    const value = values.screen[key];
    if (value === undefined) continue;
    const prefix = `min-[${theme.breakpoints[token]}]:!`;
    const variable = variableName(`screen-${token}`, property);
    style[variable] = value;
    classes.push(`${prefix}[${propertyVariableName(property)}:var(${variable})]`);
  }
}

/** Produces literal Tailwind classes or compact variable-backed classes. */
export function createLayoutTailwindStyle(
  declarations: readonly LayoutTailwindDeclaration[],
  theme: LayoutTheme,
  renderFunction = false,
  active?: LayoutActiveBreakpoints
): { className?: string; style?: CustomProperties } {
  const classes: string[] = [];
  const style: CustomProperties = {};
  let resolvedByProperty = resolveDeclarations(declarations, theme);
  if (renderFunction) {
    if (!active) throw new Error("Render-function Layout requires active breakpoints");
    resolvedByProperty = resolveActiveDeclarations(resolvedByProperty, active);
  }

  for (const [property, values] of resolvedByProperty) {
    appendSingleDeclarationClasses(classes, style, property, values, theme);
  }

  const className = [...new Set(classes)].join(" ");
  return {
    className: className || undefined,
    style: Object.keys(style).length ? style : undefined,
  };
}
