// Generated by scripts/generate-text-tailwind.mjs. Edit the generator property list instead.
import {
  LAYOUT_CONTAINER_ORDER,
  LAYOUT_VIEWPORT_ORDER,
  type LayoutResponsive,
  type LayoutResponsiveBreakpoint,
  type LayoutResponsiveKey,
} from "./layout-style-engine";

export type TextTailwindProperty =
  | "font-size"
  | "line-height"
  | "display"
  | "text-align";

export interface TextTailwindDeclaration {
  property: TextTailwindProperty;
  value: LayoutResponsive<unknown> | undefined;
  resolve: (
    value: unknown,
    breakpoint: LayoutResponsiveBreakpoint | undefined
  ) => string | undefined;
}

type BreakpointClasses = Record<string, string>;

interface PropertyClasses {
  reader: string;
  base: BreakpointClasses;
  container: Record<string, BreakpointClasses>;
  screen: Record<string, BreakpointClasses>;
}

const propertyClasses = {
  "font-size": {
    reader: "[font-size:var(--scraps-text-font-size)]",
    base: {
      "11px": "[--scraps-text-font-size:11px]",
      "12px": "[--scraps-text-font-size:12px]",
      "14px": "[--scraps-text-font-size:14px]",
      "16px": "[--scraps-text-font-size:16px]",
      "20px": "[--scraps-text-font-size:20px]",
      "24px": "[--scraps-text-font-size:24px]",
      "32px": "[--scraps-text-font-size:32px]",
      "40px": "[--scraps-text-font-size:40px]",
      "inherit": "[--scraps-text-font-size:inherit]",
    },
    container: {
      "3xs": {
        "11px": "@[320px]:[--scraps-text-font-size:11px]",
        "12px": "@[320px]:[--scraps-text-font-size:12px]",
        "14px": "@[320px]:[--scraps-text-font-size:14px]",
        "16px": "@[320px]:[--scraps-text-font-size:16px]",
        "20px": "@[320px]:[--scraps-text-font-size:20px]",
        "24px": "@[320px]:[--scraps-text-font-size:24px]",
        "32px": "@[320px]:[--scraps-text-font-size:32px]",
        "40px": "@[320px]:[--scraps-text-font-size:40px]",
        "inherit": "@[320px]:[--scraps-text-font-size:inherit]",
      },
      "2xs": {
        "11px": "@[384px]:[--scraps-text-font-size:11px]",
        "12px": "@[384px]:[--scraps-text-font-size:12px]",
        "14px": "@[384px]:[--scraps-text-font-size:14px]",
        "16px": "@[384px]:[--scraps-text-font-size:16px]",
        "20px": "@[384px]:[--scraps-text-font-size:20px]",
        "24px": "@[384px]:[--scraps-text-font-size:24px]",
        "32px": "@[384px]:[--scraps-text-font-size:32px]",
        "40px": "@[384px]:[--scraps-text-font-size:40px]",
        "inherit": "@[384px]:[--scraps-text-font-size:inherit]",
      },
      "xs": {
        "11px": "@[448px]:[--scraps-text-font-size:11px]",
        "12px": "@[448px]:[--scraps-text-font-size:12px]",
        "14px": "@[448px]:[--scraps-text-font-size:14px]",
        "16px": "@[448px]:[--scraps-text-font-size:16px]",
        "20px": "@[448px]:[--scraps-text-font-size:20px]",
        "24px": "@[448px]:[--scraps-text-font-size:24px]",
        "32px": "@[448px]:[--scraps-text-font-size:32px]",
        "40px": "@[448px]:[--scraps-text-font-size:40px]",
        "inherit": "@[448px]:[--scraps-text-font-size:inherit]",
      },
      "sm": {
        "11px": "@[512px]:[--scraps-text-font-size:11px]",
        "12px": "@[512px]:[--scraps-text-font-size:12px]",
        "14px": "@[512px]:[--scraps-text-font-size:14px]",
        "16px": "@[512px]:[--scraps-text-font-size:16px]",
        "20px": "@[512px]:[--scraps-text-font-size:20px]",
        "24px": "@[512px]:[--scraps-text-font-size:24px]",
        "32px": "@[512px]:[--scraps-text-font-size:32px]",
        "40px": "@[512px]:[--scraps-text-font-size:40px]",
        "inherit": "@[512px]:[--scraps-text-font-size:inherit]",
      },
      "md": {
        "11px": "@[576px]:[--scraps-text-font-size:11px]",
        "12px": "@[576px]:[--scraps-text-font-size:12px]",
        "14px": "@[576px]:[--scraps-text-font-size:14px]",
        "16px": "@[576px]:[--scraps-text-font-size:16px]",
        "20px": "@[576px]:[--scraps-text-font-size:20px]",
        "24px": "@[576px]:[--scraps-text-font-size:24px]",
        "32px": "@[576px]:[--scraps-text-font-size:32px]",
        "40px": "@[576px]:[--scraps-text-font-size:40px]",
        "inherit": "@[576px]:[--scraps-text-font-size:inherit]",
      },
      "lg": {
        "11px": "@[640px]:[--scraps-text-font-size:11px]",
        "12px": "@[640px]:[--scraps-text-font-size:12px]",
        "14px": "@[640px]:[--scraps-text-font-size:14px]",
        "16px": "@[640px]:[--scraps-text-font-size:16px]",
        "20px": "@[640px]:[--scraps-text-font-size:20px]",
        "24px": "@[640px]:[--scraps-text-font-size:24px]",
        "32px": "@[640px]:[--scraps-text-font-size:32px]",
        "40px": "@[640px]:[--scraps-text-font-size:40px]",
        "inherit": "@[640px]:[--scraps-text-font-size:inherit]",
      },
      "xl": {
        "11px": "@[768px]:[--scraps-text-font-size:11px]",
        "12px": "@[768px]:[--scraps-text-font-size:12px]",
        "14px": "@[768px]:[--scraps-text-font-size:14px]",
        "16px": "@[768px]:[--scraps-text-font-size:16px]",
        "20px": "@[768px]:[--scraps-text-font-size:20px]",
        "24px": "@[768px]:[--scraps-text-font-size:24px]",
        "32px": "@[768px]:[--scraps-text-font-size:32px]",
        "40px": "@[768px]:[--scraps-text-font-size:40px]",
        "inherit": "@[768px]:[--scraps-text-font-size:inherit]",
      },
      "2xl": {
        "11px": "@[896px]:[--scraps-text-font-size:11px]",
        "12px": "@[896px]:[--scraps-text-font-size:12px]",
        "14px": "@[896px]:[--scraps-text-font-size:14px]",
        "16px": "@[896px]:[--scraps-text-font-size:16px]",
        "20px": "@[896px]:[--scraps-text-font-size:20px]",
        "24px": "@[896px]:[--scraps-text-font-size:24px]",
        "32px": "@[896px]:[--scraps-text-font-size:32px]",
        "40px": "@[896px]:[--scraps-text-font-size:40px]",
        "inherit": "@[896px]:[--scraps-text-font-size:inherit]",
      },
      "3xl": {
        "11px": "@[1024px]:[--scraps-text-font-size:11px]",
        "12px": "@[1024px]:[--scraps-text-font-size:12px]",
        "14px": "@[1024px]:[--scraps-text-font-size:14px]",
        "16px": "@[1024px]:[--scraps-text-font-size:16px]",
        "20px": "@[1024px]:[--scraps-text-font-size:20px]",
        "24px": "@[1024px]:[--scraps-text-font-size:24px]",
        "32px": "@[1024px]:[--scraps-text-font-size:32px]",
        "40px": "@[1024px]:[--scraps-text-font-size:40px]",
        "inherit": "@[1024px]:[--scraps-text-font-size:inherit]",
      },
      "4xl": {
        "11px": "@[1152px]:[--scraps-text-font-size:11px]",
        "12px": "@[1152px]:[--scraps-text-font-size:12px]",
        "14px": "@[1152px]:[--scraps-text-font-size:14px]",
        "16px": "@[1152px]:[--scraps-text-font-size:16px]",
        "20px": "@[1152px]:[--scraps-text-font-size:20px]",
        "24px": "@[1152px]:[--scraps-text-font-size:24px]",
        "32px": "@[1152px]:[--scraps-text-font-size:32px]",
        "40px": "@[1152px]:[--scraps-text-font-size:40px]",
        "inherit": "@[1152px]:[--scraps-text-font-size:inherit]",
      },
      "5xl": {
        "11px": "@[1280px]:[--scraps-text-font-size:11px]",
        "12px": "@[1280px]:[--scraps-text-font-size:12px]",
        "14px": "@[1280px]:[--scraps-text-font-size:14px]",
        "16px": "@[1280px]:[--scraps-text-font-size:16px]",
        "20px": "@[1280px]:[--scraps-text-font-size:20px]",
        "24px": "@[1280px]:[--scraps-text-font-size:24px]",
        "32px": "@[1280px]:[--scraps-text-font-size:32px]",
        "40px": "@[1280px]:[--scraps-text-font-size:40px]",
        "inherit": "@[1280px]:[--scraps-text-font-size:inherit]",
      },
    },
    screen: {
      "screen:2xs": {
        "11px": "min-[0px]:![--scraps-text-font-size:11px]",
        "12px": "min-[0px]:![--scraps-text-font-size:12px]",
        "14px": "min-[0px]:![--scraps-text-font-size:14px]",
        "16px": "min-[0px]:![--scraps-text-font-size:16px]",
        "20px": "min-[0px]:![--scraps-text-font-size:20px]",
        "24px": "min-[0px]:![--scraps-text-font-size:24px]",
        "32px": "min-[0px]:![--scraps-text-font-size:32px]",
        "40px": "min-[0px]:![--scraps-text-font-size:40px]",
        "inherit": "min-[0px]:![--scraps-text-font-size:inherit]",
      },
      "screen:xs": {
        "11px": "min-[500px]:![--scraps-text-font-size:11px]",
        "12px": "min-[500px]:![--scraps-text-font-size:12px]",
        "14px": "min-[500px]:![--scraps-text-font-size:14px]",
        "16px": "min-[500px]:![--scraps-text-font-size:16px]",
        "20px": "min-[500px]:![--scraps-text-font-size:20px]",
        "24px": "min-[500px]:![--scraps-text-font-size:24px]",
        "32px": "min-[500px]:![--scraps-text-font-size:32px]",
        "40px": "min-[500px]:![--scraps-text-font-size:40px]",
        "inherit": "min-[500px]:![--scraps-text-font-size:inherit]",
      },
      "screen:sm": {
        "11px": "min-[800px]:![--scraps-text-font-size:11px]",
        "12px": "min-[800px]:![--scraps-text-font-size:12px]",
        "14px": "min-[800px]:![--scraps-text-font-size:14px]",
        "16px": "min-[800px]:![--scraps-text-font-size:16px]",
        "20px": "min-[800px]:![--scraps-text-font-size:20px]",
        "24px": "min-[800px]:![--scraps-text-font-size:24px]",
        "32px": "min-[800px]:![--scraps-text-font-size:32px]",
        "40px": "min-[800px]:![--scraps-text-font-size:40px]",
        "inherit": "min-[800px]:![--scraps-text-font-size:inherit]",
      },
      "screen:md": {
        "11px": "min-[992px]:![--scraps-text-font-size:11px]",
        "12px": "min-[992px]:![--scraps-text-font-size:12px]",
        "14px": "min-[992px]:![--scraps-text-font-size:14px]",
        "16px": "min-[992px]:![--scraps-text-font-size:16px]",
        "20px": "min-[992px]:![--scraps-text-font-size:20px]",
        "24px": "min-[992px]:![--scraps-text-font-size:24px]",
        "32px": "min-[992px]:![--scraps-text-font-size:32px]",
        "40px": "min-[992px]:![--scraps-text-font-size:40px]",
        "inherit": "min-[992px]:![--scraps-text-font-size:inherit]",
      },
      "screen:lg": {
        "11px": "min-[1200px]:![--scraps-text-font-size:11px]",
        "12px": "min-[1200px]:![--scraps-text-font-size:12px]",
        "14px": "min-[1200px]:![--scraps-text-font-size:14px]",
        "16px": "min-[1200px]:![--scraps-text-font-size:16px]",
        "20px": "min-[1200px]:![--scraps-text-font-size:20px]",
        "24px": "min-[1200px]:![--scraps-text-font-size:24px]",
        "32px": "min-[1200px]:![--scraps-text-font-size:32px]",
        "40px": "min-[1200px]:![--scraps-text-font-size:40px]",
        "inherit": "min-[1200px]:![--scraps-text-font-size:inherit]",
      },
      "screen:xl": {
        "11px": "min-[1440px]:![--scraps-text-font-size:11px]",
        "12px": "min-[1440px]:![--scraps-text-font-size:12px]",
        "14px": "min-[1440px]:![--scraps-text-font-size:14px]",
        "16px": "min-[1440px]:![--scraps-text-font-size:16px]",
        "20px": "min-[1440px]:![--scraps-text-font-size:20px]",
        "24px": "min-[1440px]:![--scraps-text-font-size:24px]",
        "32px": "min-[1440px]:![--scraps-text-font-size:32px]",
        "40px": "min-[1440px]:![--scraps-text-font-size:40px]",
        "inherit": "min-[1440px]:![--scraps-text-font-size:inherit]",
      },
      "screen:2xl": {
        "11px": "min-[2560px]:![--scraps-text-font-size:11px]",
        "12px": "min-[2560px]:![--scraps-text-font-size:12px]",
        "14px": "min-[2560px]:![--scraps-text-font-size:14px]",
        "16px": "min-[2560px]:![--scraps-text-font-size:16px]",
        "20px": "min-[2560px]:![--scraps-text-font-size:20px]",
        "24px": "min-[2560px]:![--scraps-text-font-size:24px]",
        "32px": "min-[2560px]:![--scraps-text-font-size:32px]",
        "40px": "min-[2560px]:![--scraps-text-font-size:40px]",
        "inherit": "min-[2560px]:![--scraps-text-font-size:inherit]",
      },
    },
  },
  "line-height": {
    reader: "[line-height:var(--scraps-text-line-height)]",
    base: {
      "1": "[--scraps-text-line-height:1]",
      "1.4": "[--scraps-text-line-height:1.4]",
      "inherit": "[--scraps-text-line-height:inherit]",
    },
    container: {
      "3xs": {
        "1": "@[320px]:[--scraps-text-line-height:1]",
        "1.4": "@[320px]:[--scraps-text-line-height:1.4]",
        "inherit": "@[320px]:[--scraps-text-line-height:inherit]",
      },
      "2xs": {
        "1": "@[384px]:[--scraps-text-line-height:1]",
        "1.4": "@[384px]:[--scraps-text-line-height:1.4]",
        "inherit": "@[384px]:[--scraps-text-line-height:inherit]",
      },
      "xs": {
        "1": "@[448px]:[--scraps-text-line-height:1]",
        "1.4": "@[448px]:[--scraps-text-line-height:1.4]",
        "inherit": "@[448px]:[--scraps-text-line-height:inherit]",
      },
      "sm": {
        "1": "@[512px]:[--scraps-text-line-height:1]",
        "1.4": "@[512px]:[--scraps-text-line-height:1.4]",
        "inherit": "@[512px]:[--scraps-text-line-height:inherit]",
      },
      "md": {
        "1": "@[576px]:[--scraps-text-line-height:1]",
        "1.4": "@[576px]:[--scraps-text-line-height:1.4]",
        "inherit": "@[576px]:[--scraps-text-line-height:inherit]",
      },
      "lg": {
        "1": "@[640px]:[--scraps-text-line-height:1]",
        "1.4": "@[640px]:[--scraps-text-line-height:1.4]",
        "inherit": "@[640px]:[--scraps-text-line-height:inherit]",
      },
      "xl": {
        "1": "@[768px]:[--scraps-text-line-height:1]",
        "1.4": "@[768px]:[--scraps-text-line-height:1.4]",
        "inherit": "@[768px]:[--scraps-text-line-height:inherit]",
      },
      "2xl": {
        "1": "@[896px]:[--scraps-text-line-height:1]",
        "1.4": "@[896px]:[--scraps-text-line-height:1.4]",
        "inherit": "@[896px]:[--scraps-text-line-height:inherit]",
      },
      "3xl": {
        "1": "@[1024px]:[--scraps-text-line-height:1]",
        "1.4": "@[1024px]:[--scraps-text-line-height:1.4]",
        "inherit": "@[1024px]:[--scraps-text-line-height:inherit]",
      },
      "4xl": {
        "1": "@[1152px]:[--scraps-text-line-height:1]",
        "1.4": "@[1152px]:[--scraps-text-line-height:1.4]",
        "inherit": "@[1152px]:[--scraps-text-line-height:inherit]",
      },
      "5xl": {
        "1": "@[1280px]:[--scraps-text-line-height:1]",
        "1.4": "@[1280px]:[--scraps-text-line-height:1.4]",
        "inherit": "@[1280px]:[--scraps-text-line-height:inherit]",
      },
    },
    screen: {
      "screen:2xs": {
        "1": "min-[0px]:![--scraps-text-line-height:1]",
        "1.4": "min-[0px]:![--scraps-text-line-height:1.4]",
        "inherit": "min-[0px]:![--scraps-text-line-height:inherit]",
      },
      "screen:xs": {
        "1": "min-[500px]:![--scraps-text-line-height:1]",
        "1.4": "min-[500px]:![--scraps-text-line-height:1.4]",
        "inherit": "min-[500px]:![--scraps-text-line-height:inherit]",
      },
      "screen:sm": {
        "1": "min-[800px]:![--scraps-text-line-height:1]",
        "1.4": "min-[800px]:![--scraps-text-line-height:1.4]",
        "inherit": "min-[800px]:![--scraps-text-line-height:inherit]",
      },
      "screen:md": {
        "1": "min-[992px]:![--scraps-text-line-height:1]",
        "1.4": "min-[992px]:![--scraps-text-line-height:1.4]",
        "inherit": "min-[992px]:![--scraps-text-line-height:inherit]",
      },
      "screen:lg": {
        "1": "min-[1200px]:![--scraps-text-line-height:1]",
        "1.4": "min-[1200px]:![--scraps-text-line-height:1.4]",
        "inherit": "min-[1200px]:![--scraps-text-line-height:inherit]",
      },
      "screen:xl": {
        "1": "min-[1440px]:![--scraps-text-line-height:1]",
        "1.4": "min-[1440px]:![--scraps-text-line-height:1.4]",
        "inherit": "min-[1440px]:![--scraps-text-line-height:inherit]",
      },
      "screen:2xl": {
        "1": "min-[2560px]:![--scraps-text-line-height:1]",
        "1.4": "min-[2560px]:![--scraps-text-line-height:1.4]",
        "inherit": "min-[2560px]:![--scraps-text-line-height:inherit]",
      },
    },
  },
  "display": {
    reader: "[display:var(--scraps-text-display)]",
    base: {
      "inline": "[--scraps-text-display:inline]",
      "block": "[--scraps-text-display:block]",
      "inline-block": "[--scraps-text-display:inline-block]",
      "none": "[--scraps-text-display:none]",
    },
    container: {
      "3xs": {
        "inline": "@[320px]:[--scraps-text-display:inline]",
        "block": "@[320px]:[--scraps-text-display:block]",
        "inline-block": "@[320px]:[--scraps-text-display:inline-block]",
        "none": "@[320px]:[--scraps-text-display:none]",
      },
      "2xs": {
        "inline": "@[384px]:[--scraps-text-display:inline]",
        "block": "@[384px]:[--scraps-text-display:block]",
        "inline-block": "@[384px]:[--scraps-text-display:inline-block]",
        "none": "@[384px]:[--scraps-text-display:none]",
      },
      "xs": {
        "inline": "@[448px]:[--scraps-text-display:inline]",
        "block": "@[448px]:[--scraps-text-display:block]",
        "inline-block": "@[448px]:[--scraps-text-display:inline-block]",
        "none": "@[448px]:[--scraps-text-display:none]",
      },
      "sm": {
        "inline": "@[512px]:[--scraps-text-display:inline]",
        "block": "@[512px]:[--scraps-text-display:block]",
        "inline-block": "@[512px]:[--scraps-text-display:inline-block]",
        "none": "@[512px]:[--scraps-text-display:none]",
      },
      "md": {
        "inline": "@[576px]:[--scraps-text-display:inline]",
        "block": "@[576px]:[--scraps-text-display:block]",
        "inline-block": "@[576px]:[--scraps-text-display:inline-block]",
        "none": "@[576px]:[--scraps-text-display:none]",
      },
      "lg": {
        "inline": "@[640px]:[--scraps-text-display:inline]",
        "block": "@[640px]:[--scraps-text-display:block]",
        "inline-block": "@[640px]:[--scraps-text-display:inline-block]",
        "none": "@[640px]:[--scraps-text-display:none]",
      },
      "xl": {
        "inline": "@[768px]:[--scraps-text-display:inline]",
        "block": "@[768px]:[--scraps-text-display:block]",
        "inline-block": "@[768px]:[--scraps-text-display:inline-block]",
        "none": "@[768px]:[--scraps-text-display:none]",
      },
      "2xl": {
        "inline": "@[896px]:[--scraps-text-display:inline]",
        "block": "@[896px]:[--scraps-text-display:block]",
        "inline-block": "@[896px]:[--scraps-text-display:inline-block]",
        "none": "@[896px]:[--scraps-text-display:none]",
      },
      "3xl": {
        "inline": "@[1024px]:[--scraps-text-display:inline]",
        "block": "@[1024px]:[--scraps-text-display:block]",
        "inline-block": "@[1024px]:[--scraps-text-display:inline-block]",
        "none": "@[1024px]:[--scraps-text-display:none]",
      },
      "4xl": {
        "inline": "@[1152px]:[--scraps-text-display:inline]",
        "block": "@[1152px]:[--scraps-text-display:block]",
        "inline-block": "@[1152px]:[--scraps-text-display:inline-block]",
        "none": "@[1152px]:[--scraps-text-display:none]",
      },
      "5xl": {
        "inline": "@[1280px]:[--scraps-text-display:inline]",
        "block": "@[1280px]:[--scraps-text-display:block]",
        "inline-block": "@[1280px]:[--scraps-text-display:inline-block]",
        "none": "@[1280px]:[--scraps-text-display:none]",
      },
    },
    screen: {
      "screen:2xs": {
        "inline": "min-[0px]:![--scraps-text-display:inline]",
        "block": "min-[0px]:![--scraps-text-display:block]",
        "inline-block": "min-[0px]:![--scraps-text-display:inline-block]",
        "none": "min-[0px]:![--scraps-text-display:none]",
      },
      "screen:xs": {
        "inline": "min-[500px]:![--scraps-text-display:inline]",
        "block": "min-[500px]:![--scraps-text-display:block]",
        "inline-block": "min-[500px]:![--scraps-text-display:inline-block]",
        "none": "min-[500px]:![--scraps-text-display:none]",
      },
      "screen:sm": {
        "inline": "min-[800px]:![--scraps-text-display:inline]",
        "block": "min-[800px]:![--scraps-text-display:block]",
        "inline-block": "min-[800px]:![--scraps-text-display:inline-block]",
        "none": "min-[800px]:![--scraps-text-display:none]",
      },
      "screen:md": {
        "inline": "min-[992px]:![--scraps-text-display:inline]",
        "block": "min-[992px]:![--scraps-text-display:block]",
        "inline-block": "min-[992px]:![--scraps-text-display:inline-block]",
        "none": "min-[992px]:![--scraps-text-display:none]",
      },
      "screen:lg": {
        "inline": "min-[1200px]:![--scraps-text-display:inline]",
        "block": "min-[1200px]:![--scraps-text-display:block]",
        "inline-block": "min-[1200px]:![--scraps-text-display:inline-block]",
        "none": "min-[1200px]:![--scraps-text-display:none]",
      },
      "screen:xl": {
        "inline": "min-[1440px]:![--scraps-text-display:inline]",
        "block": "min-[1440px]:![--scraps-text-display:block]",
        "inline-block": "min-[1440px]:![--scraps-text-display:inline-block]",
        "none": "min-[1440px]:![--scraps-text-display:none]",
      },
      "screen:2xl": {
        "inline": "min-[2560px]:![--scraps-text-display:inline]",
        "block": "min-[2560px]:![--scraps-text-display:block]",
        "inline-block": "min-[2560px]:![--scraps-text-display:inline-block]",
        "none": "min-[2560px]:![--scraps-text-display:none]",
      },
    },
  },
  "text-align": {
    reader: "[text-align:var(--scraps-text-text-align)]",
    base: {
      "left": "[--scraps-text-text-align:left]",
      "center": "[--scraps-text-text-align:center]",
      "right": "[--scraps-text-text-align:right]",
      "justify": "[--scraps-text-text-align:justify]",
    },
    container: {
      "3xs": {
        "left": "@[320px]:[--scraps-text-text-align:left]",
        "center": "@[320px]:[--scraps-text-text-align:center]",
        "right": "@[320px]:[--scraps-text-text-align:right]",
        "justify": "@[320px]:[--scraps-text-text-align:justify]",
      },
      "2xs": {
        "left": "@[384px]:[--scraps-text-text-align:left]",
        "center": "@[384px]:[--scraps-text-text-align:center]",
        "right": "@[384px]:[--scraps-text-text-align:right]",
        "justify": "@[384px]:[--scraps-text-text-align:justify]",
      },
      "xs": {
        "left": "@[448px]:[--scraps-text-text-align:left]",
        "center": "@[448px]:[--scraps-text-text-align:center]",
        "right": "@[448px]:[--scraps-text-text-align:right]",
        "justify": "@[448px]:[--scraps-text-text-align:justify]",
      },
      "sm": {
        "left": "@[512px]:[--scraps-text-text-align:left]",
        "center": "@[512px]:[--scraps-text-text-align:center]",
        "right": "@[512px]:[--scraps-text-text-align:right]",
        "justify": "@[512px]:[--scraps-text-text-align:justify]",
      },
      "md": {
        "left": "@[576px]:[--scraps-text-text-align:left]",
        "center": "@[576px]:[--scraps-text-text-align:center]",
        "right": "@[576px]:[--scraps-text-text-align:right]",
        "justify": "@[576px]:[--scraps-text-text-align:justify]",
      },
      "lg": {
        "left": "@[640px]:[--scraps-text-text-align:left]",
        "center": "@[640px]:[--scraps-text-text-align:center]",
        "right": "@[640px]:[--scraps-text-text-align:right]",
        "justify": "@[640px]:[--scraps-text-text-align:justify]",
      },
      "xl": {
        "left": "@[768px]:[--scraps-text-text-align:left]",
        "center": "@[768px]:[--scraps-text-text-align:center]",
        "right": "@[768px]:[--scraps-text-text-align:right]",
        "justify": "@[768px]:[--scraps-text-text-align:justify]",
      },
      "2xl": {
        "left": "@[896px]:[--scraps-text-text-align:left]",
        "center": "@[896px]:[--scraps-text-text-align:center]",
        "right": "@[896px]:[--scraps-text-text-align:right]",
        "justify": "@[896px]:[--scraps-text-text-align:justify]",
      },
      "3xl": {
        "left": "@[1024px]:[--scraps-text-text-align:left]",
        "center": "@[1024px]:[--scraps-text-text-align:center]",
        "right": "@[1024px]:[--scraps-text-text-align:right]",
        "justify": "@[1024px]:[--scraps-text-text-align:justify]",
      },
      "4xl": {
        "left": "@[1152px]:[--scraps-text-text-align:left]",
        "center": "@[1152px]:[--scraps-text-text-align:center]",
        "right": "@[1152px]:[--scraps-text-text-align:right]",
        "justify": "@[1152px]:[--scraps-text-text-align:justify]",
      },
      "5xl": {
        "left": "@[1280px]:[--scraps-text-text-align:left]",
        "center": "@[1280px]:[--scraps-text-text-align:center]",
        "right": "@[1280px]:[--scraps-text-text-align:right]",
        "justify": "@[1280px]:[--scraps-text-text-align:justify]",
      },
    },
    screen: {
      "screen:2xs": {
        "left": "min-[0px]:![--scraps-text-text-align:left]",
        "center": "min-[0px]:![--scraps-text-text-align:center]",
        "right": "min-[0px]:![--scraps-text-text-align:right]",
        "justify": "min-[0px]:![--scraps-text-text-align:justify]",
      },
      "screen:xs": {
        "left": "min-[500px]:![--scraps-text-text-align:left]",
        "center": "min-[500px]:![--scraps-text-text-align:center]",
        "right": "min-[500px]:![--scraps-text-text-align:right]",
        "justify": "min-[500px]:![--scraps-text-text-align:justify]",
      },
      "screen:sm": {
        "left": "min-[800px]:![--scraps-text-text-align:left]",
        "center": "min-[800px]:![--scraps-text-text-align:center]",
        "right": "min-[800px]:![--scraps-text-text-align:right]",
        "justify": "min-[800px]:![--scraps-text-text-align:justify]",
      },
      "screen:md": {
        "left": "min-[992px]:![--scraps-text-text-align:left]",
        "center": "min-[992px]:![--scraps-text-text-align:center]",
        "right": "min-[992px]:![--scraps-text-text-align:right]",
        "justify": "min-[992px]:![--scraps-text-text-align:justify]",
      },
      "screen:lg": {
        "left": "min-[1200px]:![--scraps-text-text-align:left]",
        "center": "min-[1200px]:![--scraps-text-text-align:center]",
        "right": "min-[1200px]:![--scraps-text-text-align:right]",
        "justify": "min-[1200px]:![--scraps-text-text-align:justify]",
      },
      "screen:xl": {
        "left": "min-[1440px]:![--scraps-text-text-align:left]",
        "center": "min-[1440px]:![--scraps-text-text-align:center]",
        "right": "min-[1440px]:![--scraps-text-text-align:right]",
        "justify": "min-[1440px]:![--scraps-text-text-align:justify]",
      },
      "screen:2xl": {
        "left": "min-[2560px]:![--scraps-text-text-align:left]",
        "center": "min-[2560px]:![--scraps-text-text-align:center]",
        "right": "min-[2560px]:![--scraps-text-text-align:right]",
        "justify": "min-[2560px]:![--scraps-text-text-align:justify]",
      },
    },
  },
} satisfies Record<TextTailwindProperty, PropertyClasses>;

function isResponsiveValue(
  value: LayoutResponsive<unknown> | undefined
): value is Partial<Record<LayoutResponsiveKey, unknown>> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** Produces literal Tailwind classes for the finite Text property values. */
export function createTextTailwindClassName(
  declarations: readonly TextTailwindDeclaration[]
): string | undefined {
  const classes: string[] = [];

  for (const declaration of declarations) {
    if (declaration.value === undefined) continue;

    const property: PropertyClasses = propertyClasses[declaration.property];
    const responsiveValue = isResponsiveValue(declaration.value)
      ? declaration.value
      : undefined;
    let wroteBase = false;

    const write = (
      key: LayoutResponsiveKey,
      breakpoint: LayoutResponsiveBreakpoint | undefined,
      candidatesAtBreakpoint: BreakpointClasses | undefined
    ) => {
      const value = responsiveValue
        ? responsiveValue[key]
        : declaration.value;
      const resolved = declaration.resolve(value, breakpoint);
      if (resolved === undefined) return;

      if (!wroteBase) {
        const baseClassName = property.base[resolved];
        if (baseClassName) {
          classes.push(property.reader, baseClassName);
          wroteBase = true;
        }
        return;
      }

      const className = candidatesAtBreakpoint?.[resolved];
      if (className) classes.push(className);
    };

    if (!responsiveValue) {
      write("zero", undefined, undefined);
      continue;
    }

    for (const key of LAYOUT_CONTAINER_ORDER) {
      write(
        key,
        key,
        key === "zero" ? undefined : property.container[key]
      );
    }

    for (const { key, token } of LAYOUT_VIEWPORT_ORDER) {
      write(key, token, property.screen[key]);
    }
  }

  const className = [...new Set(classes)].join(" ");
  return className || undefined;
}
